version: "3.8"

services:
  newage:
    image: wordpress:latest
    container_name: newage-wordpress
    restart: always
    ports:
      - "4680:80"
    env_file: .env
    volumes:
      - ./wp-content:/var/www/html/wp-content
    networks:
      - sigma-net
    depends_on:
      - newage-db

  newage-db:
    image: mariadb:10.6
    container_name: newage-db
    restart: always
    env_file: .env
    ports:
      - "127.0.0.1:4654:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sigma-net

volumes:
  db_data:

networks:
  sigma-net:
    external: true
